routes/web.php
<?php

Route::group(
[
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => ['localizationRedirect', 'localeSessionRedirect']
], 

function() {
    // Главная страница
    Route::get('/', 'MainController@index')->name('main');
    Route::get('/invite', 'MainController@loginByInvite')->name('invite.login');
    //Route::get('/passport', 'TestController@test')->name('passport.create');
    // Авторизация, регистрация, сброс пароля.
    Auth::routes(['verify' => false]);
    Route::get('/login/{network}', 'Auth\NetworkController@redirect')->name('login.network');
    Route::get('/login/{network}/callback', 'Auth\NetworkController@callback');

    // Установка валюты
    Route::get('currency/change/{currency}', 'CurrencyController@setCurrency')->where('currency', 'rub|usd|cny')->name('currency');

    // Установка локализации
    Route::get('localisation/{localisation}', 'LocalisationController@setLocalisation')->where('localisation', implode('|', config('app.locales')) )->name('localisation');

    // Личный кабинет
    Route::group(
        [
            'prefix' => 'cabinet',
            'namespace' => 'Cabinet',
            'as' => 'cabinet.',
            'middleware' => ['auth'],
        ],
        
        function () 
        {
            //Написать поставщику
            Route::get('/chat/member/{member}', 'ChatController@writeMember')->where('member', '[0-9]+')->name('chat.member');
            
            // Точка входа в личный кабинет с аутентификацией прав пользователя
            Route::get('/', 'HomeController@index')->name('home');
            
            // Личный аккаунт пользователя
            Route::resource('/account', 'AccountController')->only(['show', 'edit', 'update']);
            Route::get('/account/{account}/entrance/edit', 'AccountController@editEntrance')->where('account', '[0-9]+')->name('account.edit_entrance');
            Route::post('/account/{account}/entrance', 'AccountController@updateEntrance')->where('account', '[0-9]+')->name('account.update_entrance');
            
            // Профили пользователя
            Route::resource('/profile', 'ProfileController')->except(['index', 'create']);
            Route::get('/profile/index/{type}', 'ProfileController@index')->where('type', 'seller|buyer')->name('profile.index');
            Route::get('/profile/create/{type}', 'ProfileController@create')->where('type', 'seller|buyer')->name('profile.create');
            Route::get('/profile/{profile}/approve', 'ProfileController@approve')->where('profile', '[0-9]+')->name('profile.approve');
            Route::post('/profile/approval/{profile}', 'ProfileController@approval')->where('profile', '[0-9]+')->name('profile.approval');
            Route::get('/profile/{profile}/documents', 'ProfileController@showDocuments')->where('profile', '[0-9]+')->name('profile.show_documents');
            Route::get('/profile/{profile}/select', 'ProfileController@selectActiveProfile')->where('profile', '[0-9]+')->name('profile.select');
            Route::get('/support', 'ChatController@viewWithoutProfile')->name('chat.support');

            Route::group(['prefix' => '/{profile}', 'where' => ['profile' => '[0-9]+']], function () {
                // Менеджеры, привязанные к профилю пользователя
                Route::resource('/manager', 'ManagerController')->except(['show']);
                Route::get('/manager/{manager}/entrance/edit', 'ManagerController@editEntrance')->where('manager', '[0-9]+')->name('manager.edit_entrance');
                Route::post('/manager/{manager}/entrance', 'ManagerController@updateEntrance')->where('manager', '[0-9]+')->name('manager.update_entrance');
                
                // Товары, привязанные к профилю пользователя
                Route::resource('/product', 'ProductController')->except(['create']);
                Route::get('/product/create/choose', 'ProductController@chooseCategory')->name('product.create.choose_category');
                Route::get('/product/create/{category}/fill', 'ProductController@fillProperties')->where('category', '[0-9]+')->name('product.create.fill_properties');
                Route::get('/product/{product}/add', 'ProductController@addModel')->where('product', '[0-9]+')->name('product.add_model');
                Route::post('/product/{product}', 'ProductController@storeModel')->where('product', '[0-9]+')->name('product.store_model');
                Route::get('/product/index/inactive', 'ProductController@indexInactive')->name('product.index.inactive');
                Route::get('/product/index/deleted', 'ProductController@indexDeleted')->name('product.index.deleted');
                Route::get('/product/{product}/{model}/edit', 'ProductController@editModel')->where(['product' => '[0-9]+', 'model' => '[0-9]+'])->name('product.edit.model');
                Route::put('/product/{product}/{model}', 'ProductController@updateModel')->where(['product' => '[0-9]+', 'model' => '[0-9]+'])->name('product.update.model');
                Route::post('/product/disable/{product}', 'ProductController@disable')->where('product', '[0-9]+')->name('product.disable');
                Route::get('/product/activate/{product}', 'ProductController@activate')->where('product', '[0-9]+')->name('product.activate');
                Route::get('/product/restore/{product}', 'ProductController@restore')->where('product', '[0-9]+')->name('product.restore');
                Route::get('/product/restore/{product}/{model}', 'ProductController@restoreModel')->where(['product' => '[0-9]+', 'model' => '[0-9]+'])->name('product.restore.model');
                Route::delete('/product/delete/{product}', 'ProductController@delete')->where('product', '[0-9]+')->name('product.delete');
                Route::delete('/product/delete/{product}/{model}', 'ProductController@deleteModel')->where(['product' => '[0-9]+', 'model' => '[0-9]+'])->name('product.delete.model');
                Route::delete('/product/{product}/{model}', 'ProductController@destroyModel')->where(['product' => '[0-9]+', 'model' => '[0-9]+'])->name('product.destroy.model');
                Route::post('/product/action/make', 'ProductController@makeAction')->name('product.action');
                
                // Запросы на покупку, привязанные к профилю пользователя
                Route::resource('/request_product', 'RequestProductController')->except(['create']);
                Route::get('/request_product/create/choose', 'RequestProductController@chooseCategory')->name('request_product.create.choose_category');
                Route::get('/request_product/create/{category}/fill', 'RequestProductController@fillProperties')->where('category', '[0-9]+')->name('request_product.create.fill_properties');
                Route::post('/request_product/disable/{request_product}', 'RequestProductController@disable')->where('request_product', '[0-9]+')->name('request_product.disable');
                Route::get('/request_product/activate/{request_product}', 'RequestProductController@activate')->where('request_product', '[0-9]+')->name('request_product.activate');
                Route::delete('/request_product/delete/{request_product}', 'RequestProductController@delete')->where('request_product', '[0-9]+')->name('request_product.delete');
                Route::get('/request_product/restore/{request_product}', 'RequestProductController@restore')->where('request_product', '[0-9]+')->name('request_product.restore');
                Route::get('/request_product/index/inactive', 'RequestProductController@indexInactive')->name('request_product.index.inactive');
                Route::get('/request_product/index/deleted', 'RequestProductController@indexDeleted')->name('request_product.index.deleted');
                
                Route::post('/request_product/action/make', 'RequestProductController@makeAction')->name('request_product.action');
                
                // Экспорт
                Route::get('/export', 'ExportController@index')->name('export.index'); //ок
                Route::get('/export/create/{type}', 'ExportController@create')->name('export.create.all'); //ок
                
                Route::post('/export/page/{type}/{status}', 'ExportController@storePage')->name('export.store.page');
                Route::post('/export/all', 'ExportController@storeAll')->name('export.store.all');
                
                // Обновление данных в табличке с экспортами
                Route::get('/export/update','ExportController@updateIndex')->name('export.update');
                Route::get('/export/all/download/{export}','ExportController@download')->name('export.download');
                
                //Вьюшка с импортами
                Route::get('/import/settings/{type}/{import_id}', 'ImportController@importSettings')->where('import_id','[0-9]+')->name('import.settings');
                Route::get('/import', 'ImportController@index')->name('import.index');
                Route::get('/import/create/{type}', 'ImportController@create')->name('import.create');
                
                //Запуск импорта продуктов/запросов
                Route::get('/import/examples/table/{type}/', 'ImportController@getExampleFile')->name('import.example_file');
                Route::get('/import/examples/{type}', 'ImportController@getExampleLists')->name('import.example_lists');
                Route::post('/import/request_product/', 'ImportController@requestProductStore')->name('import.request_product');
                Route::post('/import/product/', 'ImportController@productStore')->name('import.product');
                
                //Чат
                Route::get('/chat/{tab?}', 'ChatController@view')->name('chat.index')->where('tab', 'contact|chat|search');
            });
            
            // Менеджеры, привязанные ко всем профилям пользователя

resources/views/widgets/add_product_model.blade.php
{{--
<form id="add-model-form" method="POST" accept-charset="UTF-8" class="form-vertical" enctype="multipart/form-data">
    @csrf
    
    @if (count($errors)>0) 
    <div class="text-danger">
        @foreach ($errors->all() as $error)
            <span>{{$error}}</span><br/>
        @endforeach
    </div>
    @endif

    <div class="form-group row mt-3">
        <label class="col-md-6 col-form-label">{{ __('cabinet.product.form_model_preview_image') }}</label>
        <div class="col-sm-6">
            <input type="file" name="preview_image" accept="image/*" value="{{ old('preview_image') }}">
        </div>
    </div>
    <div class="form-group row">
        <label for="example-email-input" class="col-12 col-md-6 col-form-label">{{ __('cabinet.product.form_color') }}</label>
        <div class="col-12 col-md-6">
            <select name="color">
                @foreach($colors as $color)
                    <option value="{{ $color->code }}">{{ $color->value }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-group row">
        <div class="input-group">
            <label for="example-text-input" class="col-12 col-md-6 col-form-label">{{ __('cabinet.product.form_available') }}</label>
            <div class="col-12 col-md-6">
                <div class="row">
                    <div class="col-5">
                        <input class="form-control" name="available[value]" type="text" value="" >
                    </div>
                    <div class="col-2">
                        <select class="h-100" name="available[type]">
                            @foreach($quantities as $quantity)
                                <option value="{{ $quantity->code }}">{{ $quantity->value }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <label for="example-text-input" class="col-12 col-md-6 col-form-label">{{ __('cabinet.product.form_min_price') }}, ($)</label>
        <div class="col-12 col-md-6">
            <input class="form-control" name="min_price" type="text" value="{{ old('min_price') }}" >
        </div>
    </div>	
    <div class="form-group row">
        <label for="example-text-input" class="col-12 col-md-6 col-form-label">{{ __('cabinet.product.form_max_price') }}, ($)</label>
        <div class="col-12 col-md-6">
            <input class="form-control" name="max_price" type="text" value="{{ old('max_price') }}" >
        </div>
    </div>
    
    <hr class="mt-5">
    <div class="form-group row justify-content-center">
        <button type="button" id="delete-model" class="btn btn-secondary mt-3 mr-5">{{ __('interface.buttons.delete') }}</button>
    </div>
</form>

<div id="button-wrapper" class="row">
    <button type="button" id="add-model" class="btn btn-secondary mt-3 mr-5">{{ __('interface.buttons.add_more') }}</button>
    <button type="button" id="save-models" data-action="{{ $action }}" class="btn btn-secondary mt-3">{{ __('interface.buttons.save') }}</button>
</div>
--}}

<form id="add-model-form" method="POST" accept-charset="UTF-8" enctype="multipart/form-data" class="cabinet__createModel__model">
    @csrf
    <div class="cabinet__createModel__section cabinet__createModel__content form">
        
        <div class="cabinet__subtitle">{{ __('cabinet.product.form_add_product_model') }} {{ $productArticul }} — <span class="prefix">{{ $articulPrefix }}</span></div>
        
        <div class="form__row form__row-required">
            <div class="form__row__uploadImages">
                <div class="form__row__uploadImages__label">{{ __('cabinet.product.form_model_preview_image') }}</div>

                <input id="preview-image" type="file" class="form__row__uploadFile__input" name="preview_image" accept="image/*">
                
                <label for="preview-image" class="form__row__uploadFile__label">
                    <div class="button button-primary-bordered button-inline">{{ __('interface.buttons.choose_image') }}</div>
                </label>
            </div>
            <div class="form__row__error"></div>
        </div>
        
        <div class="form__double__row form__double__row-between">
                        
            <div class="form__row form__row-required">
                <input name="min_price" type="text" value="{{ old('min_price') }}" class="form__row__input" id="min-price" required>
                <label for="min-price" class="form__row__label">{{ __('cabinet.product.form_min_price') }}, ($)</label>
                <div class="form__row__error"></div>
            </div>
            
            <div class="form__row">
                <input name="max_price" type="text" value="{{ old('max_price') }}" class="form__row__input" id="max-price">
                <label for="max-price" class="form__row__label">{{ __('cabinet.product.form_max_price') }}, ($)<label>
                <div class="form__row__error"></div>
            </div>
            
        </div>
        
        <div class="form__double__row form__double__row-between">
                        
            <div class="form__row form__row-required">
                <input type="text" name="available[value]" class="form__row__input" id="available-value" value="{{ old('available[value]') }}" required>
                <label for="available-value" class="form__row__label">{{ __('cabinet.product.form_available') }}</label>
                <div class="form__row__error"></div>
            </div>
            
            <div class="form__row form__row-required">
                <select name="available[type]">
                    @foreach($quantities as $quantity)
                    <option 
                        value="{{ $quantity->code }}" 
                        {{ (old('available[type]') === $quantity->code) ? 'selected' : '' }}
                    >
                        {{ $quantity->value }}
                    </option>
                    @endforeach
                </select>
            </div>
            
        </div>
        
        <div class="form__row form__row-required">
            <div class="form__row__selectorColor">
                <div class="form__row__selectorColor__label">{{ __('cabinet.product.form_color') }}</div>
                <div class="form__row__selectorColor__content">
                    <select name="color" class="colorpicker-handle">
                        @foreach($colors as $color)
                        <option {{(request('color') === $color->code) ? 'selected' : ''}} value="{{ $color->code }}">{{ $color->value }}</option>
                        @endforeach
                    </select>
                </div>  
            </div>
        </div>
                    
        <div class="cabinet__createModel__actions">
            <button type="button" id="delete-model" class="button button-primary-bordered button-inline d-none">
                {{ __('interface.buttons.delete') }}
            </button>
        </div>

    </div>
</form>

resources/views/widgets/approve_profile.blade.php
<div class="card border-0">
    <div class="card-header"> 
        {{ __('cabinet.profile.not_approved') }}
    </div>
    <div class="card-body"> 
        {{ __('cabinet.profile.requre_approve') }}
    </div>
    <div class="card-footer"> 
        <a href="{{ route('cabinet.profile.index') }}" class="btn btn-secondary">{{ __('interface.buttons.goto_profiles') }}</a>
    </div>
</div>

resources/views/widgets/breadcrumbs.blade.php
@if (count($breadcrumbs))    
    
    <div class="breadcrumbs">
		<ul>
			@foreach ($breadcrumbs as $breadcrumb)

                @if ($breadcrumb->url && !$loop->last)
                    <li><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
                @else
                    <li>{{ $breadcrumb->title }}</li>
                @endif

            @endforeach
		</ul>
	</div>

@endif

resources/views/widgets/filter_favorites.blade.php
{{--
<form id="filter-favorites" action="?" method="GET">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-4">
                    <input type="text" name="name" placeholder="{{ __('interface.filters.favourite_name') }}" class="w-100" value="{{ request('name') }}">
                </div>
                
                <div class="col-4">
                    <select class="select2 categories w-100 filter" name="category_id">
                        <option {{ request('category_id') ? '' : 'selected' }}></option>
                        @foreach($categories as $category)
                        <option {{ (request('category_id') == $category['id']) ? 'selected' : '' }} value="{{ $category['id'] }}">{{ $category['text'] }}</option>
                        @endforeach
                    </select>
                </div>
                
                <div class="col-4">
                <button type="submit" class="btn btn-primary"> {{ __('interface.buttons.search') }}</button>
                    <button id="filter-favorites-reset" type="button" class="btn btn-light mr-5">{{ __('interface.buttons.clear') }}</button>
                </div>
            </div>
        </div>
    </div>
</form>
--}}

<div class="cabinet__content__filter">
    <div class="cabinet__content__filter__row cabinet__content__filter__row-space-between">
        <form id="filter-favorites" action="?" method="GET">
            <div class="cabinet__content__filter__search">
                
                <input 
                    type="text" 
                    class="cabinet__content__filter__search__input" 
                    placeholder="{{ __('interface.filters.search_' . request()->route('type')) }}" 
                    value="{{ request('name') }}"
                    name="name"
                >

                <div 
                    class="cabinet__content__filter__search__more cabinet__content__filter__search__more-active"
                >
                    
                    <div class="cabinet__content__filter__search__more__row">

                        <div class="cabinet__content__filter__search__more__row__element">
                            
                            <select id="favorites-category-id" class="filter" name="category_id">
                                <option {{ request('category') ? '' : 'selected' }}></option>
                                @foreach($categories as $category)
                                <option {{ (request('category_id') == $category['id']) ? 'selected' : '' }} value="{{ $category['id'] }}">
                                    {{ $category['text'] }}
                                </option>
                                @endforeach
                            </select>
                            
                        </div>
                        
                    </div>

                </div>
                
                <button type="submit" class="button button-primary button-inline">{{ __('interface.buttons.search') }}</button>
                <button id="filter-favorites-reset" type="button" class="button button-inline button-primary-bordered">{{ __('interface.buttons.clear') }}</button>
                
            </div>
        </form>
 
    </div>
</div>

resources/views/widgets/filter_products.blade.php
{{--
<form id="filter-products" action="?" method="GET">
    <div class="card">
    
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <div class="card-body">
            <div class="row ml-0">
                <input type="text" name="name" placeholder="{{ __('interface.filters.search_product') }}" class="w-75" value="{{ request('name') }}">
            </div>
        </div>
        
        <div class="card-body {{ $area === 'show' ? '' : 'd-none' }}" data-area="{{ $area === 'show' ? 'show' : 'hide' }}" id="full-filter-products">
            <div class="row">
                <div class="col-4">
                    <label>@isset($id){{ __('interface.filters.number') }}@else{{ __('interface.filters.articul') }}@endisset</label>
                    <input type="text" name="@isset($id){{'id'}}@else{{'articul'}}@endisset" class="mr-4 w-100 filter" {{ $area === 'show' ? '' : 'disabled' }} value="{{ request('articul') }}">
                </div>
                
                <div class="col-4">
                    <label>{{ __('interface.filters.category') }}</label>
                    <select class="select2 categories w-100 filter" name="category" {{ $area === 'show' ? '' : 'disabled' }}>
                        <option {{ request('category') ? '' : 'selected' }}></option>
                        @foreach($categories as $category)
                        <option {{ (request('category') == $category['id']) ? 'selected' : '' }} value="{{ $category['id'] }}">{{ $category['text'] }}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <label class="mt-3">{{ __('interface.filters.price') }}, $</label>
            <div class="row">
                <div class="col-4 d-flex justify-content-between">
                    <span>{{ __('interface.filters.min_price') }}</span>
                    <input type="text" name="min_price" class="w-25 mr-5 filter" {{ $area === 'show' ? '' : 'disabled' }} value="{{ request('min_price') }}">
                    <span>{{ __('interface.filters.max_price') }}</span>
                    <input type="text" name="max_price" class="w-25 filter" {{ $area === 'show' ? '' : 'disabled' }} value="{{ request('max_price') }}">
                </div>
            </div>

        </div>
        
        <div class="card-body">
            <div class="row">
                <div class="col-8">
                    <button type="submit" class="btn btn-primary">{{ __('interface.buttons.search') }}</button>
                    <a href="{{ Request::url() }}" class="btn btn-light mr-5">{{ __('interface.buttons.clear') }}</a>
                    <button type="button" class="btn border" data-hide="{{ __('interface.filters.hide') }}" data-show="{{ __('interface.filters.detail') }}" data-area="{{ $area === 'hide' ? 'hide' : 'show' }}" id="toggle-filter-products">
                        {{ $area === 'show' ? __('interface.filters.hide') : __('interface.filters.detail')}}
                    </button>
                    <input name="full_filter" type="hidden" value="{{ $area === 'show' ? 'show' : 'hide' }}">
                </div>
            </div>
        </div>
        
    </div>
</form>
--}}

<div class="cabinet__content__filter">
    <div class="cabinet__content__filter__row cabinet__content__filter__row-space-between">
        <form id="filter-products" action="?" method="GET">
            <div class="cabinet__content__filter__search">
                
                <input 
                    type="text" 
                    class="cabinet__content__filter__search__input" 
                    placeholder="{{ __('interface.filters.search_product') }}" 
                    value="{{ request('name') }}"
                    name="name"
                >
                
                <!-- При активации добавляется класс cabinet__content__filter__search__more-active -->
                <div 
                    class="cabinet__content__filter__search__more {{ $area === 'show' ? 'cabinet__content__filter__search__more-active' : '' }}"
                    data-area="{{ $area === 'show' ? 'show' : 'hide' }}" 
                    id="full-filter-products"
                >
                    
                    <div class="cabinet__content__filter__search__more__row">

                        <div class="cabinet__content__filter__search__more__row__element">
                        {{-- <label for="category">{{ __('interface.filters.category') }}</label> --}}
                            
                            <select id="category" class="filter" name="category" {{ $area === 'show' ? '' : 'disabled' }}>
                                <option {{ request('category') ? '' : 'selected' }}></option>
                                @foreach($categories as $category)
                                <option {{ (request('category') == $category['id']) ? 'selected' : '' }} value="{{ $category['id'] }}">
                                    {{ $category['text'] }}
                                </option>
                                @endforeach
                            </select>
                            
                        </div>
                        
                    </div>
                    
                    <div class="cabinet__content__filter__search__more__row">
                        
                        <div class="cabinet__content__filter__search__more__row__element">
                        {{--
                            <label for="articul">
                                {{ __('interface.filters.articul') }}
                            </label>
                        --}}    
                            <input type="text" id="articul" class="filter" value="{{ request('articul') }}" {{ $area === 'show' ? '' : 'disabled' }} placeholder="{{ __('interface.filters.articul') }}" name="articul">
                            
                        </div>

                    </div>
                    
                    <div class="cabinet__content__filter__search__more__row priceRange">
                        <div class="cabinet__content__filter__search__more__row__element">
                        {{-- <span>{{ __('interface.filters.min_price') }}</span> --}}
                            <input type="text" class="filter" name="min_price" {{ $area === 'show' ? '' : 'disabled' }} value="{{ request('min_price') }}" placeholder="{{ __('interface.filters.min_price') }}">
                        </div>
                        <div class="cabinet__content__filter__search__more__row__element">
                        {{-- <span>{{ __('interface.filters.max_price') }}</span> --}}
                            <input type="text" class="filter" name="max_price" {{ $area === 'show' ? '' : 'disabled' }} value="{{ request('max_price') }}" placeholder="{{ __('interface.filters.max_price') }}">
                        </div>
                    </div>
                    
                </div>
                
                <button type="submit" class="button button-primary button-inline">{{ __('interface.buttons.search') }}</button>
                <a href="{{ Request::url() }}" class="button button-inline button-primary-bordered">{{ __('interface.buttons.clear') }}</a>
                <input name="full_filter" type="hidden" value="{{ $area === 'show' ? 'show' : 'hide' }}">
                
            </div>
        </form>
        
        <!-- При активации добавляется класс cabinet__content__filter__showDetailFilter-active -->
        <div 
            class="cabinet__content__filter__showDetailFilter cabinet__content__filter__showDetailFilter-active"
            id="toggle-filter-products"
            data-hide="{{ __('interface.filters.hide') }}"
            data-show="{{ __('interface.filters.detail') }}"
            data-area="{{ $area === 'hide' ? 'hide' : 'show' }}"
        >
            {{ $area === 'show' ? __('interface.filters.hide') : __('interface.filters.detail') }}
        </div>
        
    </div>
</div>

resources/views/widgets/pagination.blade.php
@if ($paginator->hasPages())
    <div class="catalog__pagination">
        <ul>
            {{-- Previous Page Link --}}
            @if ($paginator->onFirstPage())

            @else
                <li class="catalog__pagination__item catalog__pagination__item-prev">
                    <a href="{{ $paginator->previousPageUrl() }}">@lang('pagination.previous')</a>
                </li>
            @endif

            {{-- Pagination Elements --}}
            @foreach ($elements as $element)
                {{-- "Three Dots" Separator --}}
                @if (is_string($element))
                    <li class="catalog__pagination__item disabled" aria-disabled="true"><span class="page-link">{{ $element }}</span></li>
                @endif

                {{-- Array Of Links --}}
                @if (is_array($element))
                    @foreach ($element as $page => $url)
                        @if ($page == $paginator->currentPage())
                            <li class="catalog__pagination__item catalog__pagination__item-active" aria-current="page"><span class="page-link">{{ $page }}</span></li>
                        @else
                            <li class="catalog__pagination__item"><a class="page-link" href="{{ $url }}">{{ $page }}</a></li>
                        @endif
                    @endforeach
                @endif
            @endforeach

            {{-- Next Page Link --}}
            @if ($paginator->hasMorePages())
                <li class="catalog__pagination__item catalog__pagination__item-next">
                    <a href="{{ $paginator->nextPageUrl() }}">@lang('pagination.next')</a>
                </li>
            @else

            @endif
        </ul>
    </div>
@endif